"""Added blogposts table

Revision ID: 3b1a901239af
Revises: 736d034f9c9e
Create Date: 2019-01-31 22:22:14.930823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b1a901239af'
down_revision = '736d034f9c9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogposts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mongo_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blogposts_mongo_id'), 'blogposts', ['mongo_id'], unique=True)
    op.create_index(op.f('ix_blogposts_title'), 'blogposts', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blogposts_title'), table_name='blogposts')
    op.drop_index(op.f('ix_blogposts_mongo_id'), table_name='blogposts')
    op.drop_table('blogposts')
    # ### end Alembic commands ###
