"""Initial migration

Revision ID: f10c7b5d75d6
Revises: 
Create Date: 2019-02-10 14:12:17.024827

"""
from alembic import op
import sqlalchemy as sa
from werkzeug.security import generate_password_hash
import os
import time 

# revision identifiers, used by Alembic.
revision = 'f10c7b5d75d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    roles_table = op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    users_table = op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('blogposts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mongo_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('url', sa.String(length=64), nullable=True),
    sa.Column('author', sa.String(length=64), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blogposts_author'), 'blogposts', ['author'], unique=False)
    op.create_index(op.f('ix_blogposts_mongo_id'), 'blogposts', ['mongo_id'], unique=True)
    op.create_index(op.f('ix_blogposts_title'), 'blogposts', ['title'], unique=True)
    op.create_index(op.f('ix_blogposts_url'), 'blogposts', ['url'], unique=True)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_timestamp'), 'posts', ['timestamp'], unique=False)
    # ### end Alembic commands ###

    ### Initial seed data

    op.bulk_insert(
        roles_table,
        [
            {
                'id'           : 1,
                'name'         : 'User',
                'default'      : True,
                'permissions'  : 7
            },
            {
                'id'           : 2,
                'name'         : 'Moderator',
                'default'      : False,
                'permissions'  : 15
            },
            {
                'id'           : 3,
                'name'         : 'Administrator',
                'default'      : False,
                'permissions'  : 31
            }
        ]
    )
    op.bulk_insert(
        users_table,
        [
            {
                'id'                : 1,
                'email'             : os.environ.get('ADMIN'),
                'username'          : os.environ.get('ADMIN_USERNAME'),
                'password_hash'     : '{}'.format(generate_password_hash(os.environ.get('ADMIN_PASSWORD'))), 
                'confirmed'         : True,
                'about_me'          : '',
                'member_since'      : '{}'.format(time.strftime('%Y-%m-%d %H:%M:%S')),
                'last_seen'         : '{}'.format(time.strftime('%Y-%m-%d %H:%M:%S')),
                'role_id'           : 3                
            }
        ]
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_timestamp'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_blogposts_url'), table_name='blogposts')
    op.drop_index(op.f('ix_blogposts_title'), table_name='blogposts')
    op.drop_index(op.f('ix_blogposts_mongo_id'), table_name='blogposts')
    op.drop_index(op.f('ix_blogposts_author'), table_name='blogposts')
    op.drop_table('blogposts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
